### ISSUE TITLE
Product is Engine Professional NOT Employee Professional

### ISSUE THREAD

**Issue by stellaballa** [stellaballa/EP#1]
@sagarpc This project is not called Employee Professional. Can you please change any reference that say employee professional? I can't show this to client until this has been updates.
This include URL for example: http://71.13.159.202/aerastage/EmployeeProfessional.aspx

![screen shot 2018-11-05 at 12 12 26 pm](https://user-images.githubusercontent.com/30122790/48023958-25770800-e0f4-11e8-9832-eca67b2f1cfd.png)

**Comment by SagarPC** [comment]
@stellaballa : updated URL name.

http://71.13.159.202/aerastage/EngineProfessional.aspx
