### ISSUE TITLE
Thank you email

### ISSUE THREAD

**Issue by stellaballa** [stellaballa/EP#10]
This is ugly can we fix it. 
![screen shot 2018-11-05 at 2 28 44 pm](https://user-images.githubusercontent.com/30122790/48030841-2e250980-e107-11e8-894d-9a89491ad353.png)

**Comment by SagarPC** [comment]
@stellaballa : 

Kindly share email content for the below process. We already requested same inside basecamp many numbers of time.

- Thank you email to the user.
- Notify admin that new user requested for EP subscription.
- Notify admin that user has been successfully upgraded his subscription.
- Admin User has been successfully subscribed with change info.

**Comment by stellaballa** [comment]
The email is looking better, but why there are so many different font sizes? 
Dear Stella is bigger then the body copy.
Thanks is bold. 

Can you replace Thanks with this:
Sincerely,
Amanda
Circulation & Communication Specialist

Use this at the bottom
AN AERA INTERNATIONAL QUARTERLY PUBLICATION 
875 Feinberg Court, Suite 106, Cary, IL 60013 USA
toll-free 888.326.2372 or 815.526.7600 
Fax 888.329.2372 or 815.526.7601 
© AERA Engine Builders Association. All rights reserved. 


![screen shot 2018-11-06 at 4 22 55 pm](https://user-images.githubusercontent.com/30122790/48102542-63e9f100-e1e0-11e8-8875-7e2901e5fe14.png)

**Comment by anthonypartsconnect** [comment]
@SagarPC 

Please make these changes and let us know if you have any questions.  Thank you.

**Comment by SagarPC** [comment]
Updated email format and content as suggested. Please refer below image.

![image](https://user-images.githubusercontent.com/31076567/48485458-e9a01900-e83e-11e8-8fe3-d83eee03430e.png)

**Comment by stellaballa** [comment]
@anthonypartsconnect please check
