### ISSUE TITLE
Change Tab Name to EP

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#11]
![image](https://user-images.githubusercontent.com/26386841/48231064-a5aaa100-e372-11e8-8206-6317d7d53281.png)
Can we update the name from Engine Pro to EP?

**Comment by anthonypartsconnect** [comment]
@Sagar, Please make this change for Amanda. Change the tab from "Engine Professional" to "EP"

Thank you!

**Comment by SagarPC** [comment]
@anthonypartsconnect : We changed the tab name as suggested.

![image](https://user-images.githubusercontent.com/31076567/48485542-29ff9700-e83f-11e8-88bb-47ace9d5c073.png)

**Comment by amandagoyette** [comment]
Looks good thanks Sagar!
