### ISSUE TITLE
Subscription Email Logo & Text

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#12]
![image](https://user-images.githubusercontent.com/26386841/48231418-a3951200-e373-11e8-97fc-24b1ad3753a7.png)

I'm not sure what the image is supposed to be, I think the Engine Professional logo, but it's broken. 

Can we update to read: 
This email is to notify you that your subscription request for Engine Professional has been accepted. 

Thank you,

Amanda Harmening
Circulation Specialist
AERA Engine Builders Association
www.aera.org

**Comment by anthonypartsconnect** [comment]
@SagarPC 

Please see broken image screenshot. 
Please see Amanda's comment above.  The updated copy should read:

"This email is to notify you that your subscription request for Engine Professional has been accepted."

Please let me know if you have any questions.

**Comment by stellaballa** [comment]
@anthonypartsconnect testing this.

**Comment by SagarPC** [comment]
updated email content.

![image](https://user-images.githubusercontent.com/31076567/48488365-9af67d00-e846-11e8-86d1-9fce390d0ac8.png)

**Comment by amandagoyette** [comment]
I've tested the image and it's working now.

@SagarPC can we make the text at the bottom a little larger looks like right now it's an 8.5pt maybe up it to 10pt

Also, if they reply to the email it should go to me: amanda@aera.org instead of Karen.

**Comment by SagarPC** [comment]
made larger text at the bottom and set reply-to amanda@aera.org.

![image](https://user-images.githubusercontent.com/31076567/48544765-59b7a900-e8ea-11e8-8b3c-50dc18492de3.png)

**Comment by aharmening** [comment]
![image](https://user-images.githubusercontent.com/26386841/48573756-d8a0e780-e8d2-11e8-92c8-33ede5099599.png)

Reply to is good and so it text size. For some reason my Subject has Professional mis-spelled even though Sagar's doesn't. We need to fix that. 

Also, Sagar's shows the correct Title for me, but mine is still showing the old one. We need to make sure it reads: Circulation Specialist

**Comment by amandagoyette** [comment]
Only update here is change EP to Engine Professional:
![image](https://user-images.githubusercontent.com/26386841/48574156-0c304180-e8d4-11e8-9fb2-d5dd5000f7f1.png)

**Comment by SagarPC** [comment]
changed EP to Engine Professional
![image](https://user-images.githubusercontent.com/31076567/48624140-b93cb400-e9d1-11e8-8755-be82c8161b55.png)

**Comment by kbt1** [comment]
that looks good.
