### ISSUE TITLE
Update Header 

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#13]
![image](https://user-images.githubusercontent.com/26386841/48231821-1d79cb00-e375-11e8-92ed-1eea7d22c216.png)

Please update the word Member in the circled section to read subscriber

**Comment by anthonypartsconnect** [comment]
@SagarPC 
Please see the image from Amanda and correct word "member" with "subscriber" in the email renewal.

**Comment by SagarPC** [comment]
updated text as suggested. please refer below image.

![image](https://user-images.githubusercontent.com/31076567/48486514-c165e980-e841-11e8-96c0-abdfa4470447.png)

**Comment by amandagoyette** [comment]
Looks good thanks!
