### ISSUE TITLE
Fix text 

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#14]
I know I mentioned this in the meeting, but thought I'd get it in the queue:
![image](https://user-images.githubusercontent.com/26386841/48231983-c45e6700-e375-11e8-8d95-bb6d480a4c58.png)
We need to fix the word Professional

**Comment by anthonypartsconnect** [comment]
@Sagar, 

Please update the work "Profression" to "Professional"

![image](https://user-images.githubusercontent.com/39140696/48380515-e36a3b00-e68c-11e8-80cf-5ead51572cd9.png)

**Comment by amandagoyette** [comment]
I just noticed subscribed is misspelled also.

Amanda Harmening
AERA Engine Builders Association

________________________________

**Comment by SagarPC** [comment]
corrected typo.

![image](https://user-images.githubusercontent.com/31076567/48486838-9334d980-e842-11e8-9ca1-e8176bf313b1.png)

**Comment by amandagoyette** [comment]
Looks good. Thanks!
