### ISSUE TITLE
Update Subscription Email

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#16]
We need to fix the spelling and text on this email including the subject line. 
![image](https://user-images.githubusercontent.com/26386841/48232309-ca087c80-e376-11e8-872c-7f86f6460d76.png)
 
Subject: Engine Professional Subscription
Body: Thank you for updating your subscription to Engine Professional Magazine. 

Sincerely,

Amanda Harmening
Circulation Specialist
AERA Engine Builders Association

**Comment by anthonypartsconnect** [comment]
@SagarPC 
Please see the changes that Amanda added. Let me know if you have any questions. If not, please correct. 

Thank you!!

**Comment by amandagoyette** [comment]
Also, the replies to this email should go to me: amanda@aera.org, not info@aera.org

**Comment by stellaballa** [comment]
@SagarPC please update

**Comment by SagarPC** [comment]
update content and set the reply to amanda@aera.org

![image](https://user-images.githubusercontent.com/31076567/48545363-bebfce80-e8eb-11e8-8350-9bd183e3c2bd.png)

**Comment by amandagoyette** [comment]
![image](https://user-images.githubusercontent.com/26386841/48573987-962bda80-e8d3-11e8-99ad-7788af0164ce.png)
Reply to is correct. We just need to fix the spelling of Professional and update my title to Circulation Specialist

**Comment by SagarPC** [comment]
corrected typo and updated title to Circulation Specialist.

![image](https://user-images.githubusercontent.com/31076567/48624825-7976cc00-e9d3-11e8-81d9-f2571095c6bf.png)

**Comment by kbt1** [comment]
looks good.
