### ISSUE TITLE
Add ability to search by city

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#17]

**Comment by anthonypartsconnect** [comment]
@ Sagar, 

Hello. 

Amanda requested that we add ability to search by city.  Please let us know if we can change this and if we need to add a city column to this section. 

![image](https://user-images.githubusercontent.com/39140696/48381246-eb77aa00-e68f-11e8-901e-a2ab80bf6505.png)


Thanks.

**Comment by stellaballa** [comment]
@SagarPC

**Comment by SagarPC** [comment]
We added search by City option inside EP tab search. Please refer below image.

![image](https://user-images.githubusercontent.com/31076567/48545529-1c541b00-e8ec-11e8-878a-ae8cd7d0205f.png)

**Comment by amandagoyette** [comment]
Thank you I've tested it and it is working.
