### ISSUE TITLE
Update List dropdown

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#18]
Please add the following to the List Drop down:
Show/Conf
ExpMbr
Advertising
Rock Products
Assoc/Group

**Comment by anthonypartsconnect** [comment]
Hi Amanda, 

Can you please clarify what you need here.  

Are you asking to add a dropdown?  Would these items be under the "view" button for each record?

**Comment by amandagoyette** [comment]
No, not add a drop down just add to it. This ticket is for List and there's another for the box next to it which is Type.  Does that help?
![image](https://user-images.githubusercontent.com/26386841/48383567-eaed0c80-e6ab-11e8-8235-c15ca69755df.png)

**Comment by anthonypartsconnect** [comment]
Thank you for the clarification Amanda. I will push this to Sagar for updates.

**Comment by anthonypartsconnect** [comment]
@SagarPC 
Hi Sagar, 

Please see Amanda's screenshot and request to add to the list dropdown in the edit section of a user. The entries we would like added are: 
Show/Conf
ExpMbr
Advertising
Rock Products
Assoc/Group

Please let me know if you have any questions. 

Thank you.

**Comment by SagarPC** [comment]
updated List dropdown

![image](https://user-images.githubusercontent.com/31076567/48545699-8c62a100-e8ec-11e8-8537-41a5680895e4.png)

**Comment by amandagoyette** [comment]
Looks good. thanks!
