### ISSUE TITLE
Update Type Drop Down

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#19]
Please change ASOC to Assoc

Also add (these are in no particular order maybe we can alphabetize both lists):
Online
Phone
Fax
Email
AC
Author
B
VT
Gov
Perf Shop
Rep

**Comment by anthonypartsconnect** [comment]
@SagarPC 
Under the edit section for a subscriber, can we update the type dropdown by adding Amanda's list and changing "ASOC" to "Assoc".  Can we also please alphabetize the entire dropdown list too? 
![image](https://user-images.githubusercontent.com/39140696/48385031-c1c77e80-e6a1-11e8-8828-3c9c2649f431.png)

Thank you.

**Comment by SagarPC** [comment]
updated type dropdown
![image](https://user-images.githubusercontent.com/31076567/48547459-adc58c00-e8f0-11e8-8623-392b91718610.png)

**Comment by amandagoyette** [comment]
Looks good. THanks!
