### ISSUE TITLE
Registration Form

### ISSUE THREAD

**Issue by stellaballa** [stellaballa/EP#2]
Please see comments on this image. And use the footer image as reference for logo size. 
![screen shot 2018-11-05 at 12 15 24 pm](https://user-images.githubusercontent.com/30122790/48024390-67ed1480-e0f5-11e8-9378-dfb2147f2d05.png)

![screen shot 2018-11-05 at 12 15 41 pm](https://user-images.githubusercontent.com/30122790/48024353-50159080-e0f5-11e8-9534-c0b60137ce4e.png)

**Comment by SagarPC** [comment]
@stellaballa : updated logo size on page.

http://71.13.159.202/aerastage/EngineProfessional.aspx

![image](https://user-images.githubusercontent.com/31076567/48064707-9e5a8a80-e1ee-11e8-8c73-4203651a9673.png)
