### ISSUE TITLE
Expiration Date

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#20]
![image](https://user-images.githubusercontent.com/26386841/48288107-a3a71780-e430-11e8-8236-1ffd95281b5d.png)
When I update the Requested Date it should update the Expiration Date accordingly.

**Comment by anthonypartsconnect** [comment]
@aharmening 
Hi Amanda, can you clarify the error you are seeing here.  Is the start date not reflecting the accurate exp date?  I see your note about adding per online req 4/30/18.  

Please elaborate on this issue so we can fix.  

Thanks.

**Comment by amandagoyette** [comment]
In the image there's an incorrect expiration date. I updated their request date from 4/30/18 to 11/9/18. The new expiration date should have been 11/9/2021, but it didn't change. When the request date changes the expiration date should update too. 
Does that help @anthonypartsconnect

**Comment by anthonypartsconnect** [comment]
Thank you Amanda. Knowing your action, now the exp date issue makes sense.  We will get this fixed. 

@SagarPC 
Sagar, please update so that when a new request date is entered, the appropriate expiration date follows. 

Thanks.

**Comment by SagarPC** [comment]
Now on Expiration Date updated accordingly based on Requested Date. Please refer below image.

![image](https://user-images.githubusercontent.com/31076567/48547819-815e3f80-e8f1-11e8-94f9-957a784ff57e.png)

**Comment by amandagoyette** [comment]
Thanks. Tested and it's working
