### ISSUE TITLE
Change Title of Report

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#21]
![image](https://user-images.githubusercontent.com/26386841/48288497-ee755f00-e431-11e8-89e1-299c8b305f5d.png)
Please change the name of the highlighted report to 1 Issue Left

**Comment by anthonypartsconnect** [comment]
@Sagar, 

Can you make this change Sagar, thanks.

**Comment by stellaballa** [comment]
@SagarPC

**Comment by SagarPC** [comment]
We changed the text as per the EP tab screen to keep consistency. Please let me know if any change.

![image](https://user-images.githubusercontent.com/31076567/48548060-0ba6a380-e8f2-11e8-8465-7242b63ac464.png)

**Comment by amandagoyette** [comment]
This is good to go
