### ISSUE TITLE
Email Blast Report

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#22]
Can we add the Company field to this list?

**Comment by anthonypartsconnect** [comment]
@SagarPC 
For Amanda's request, can you please make the change to email blast report, by adding "Company" or "Company Name" to the fields?

**Comment by SagarPC** [comment]
We added "Company Name" field to the Email Blast Report.

**Comment by amandagoyette** [comment]
Company is added, thanks. 
 Is it possible to split the first and last name into separate columns for this report only? That way it matches the format of Constant Contact.

**Comment by SagarPC** [comment]
now the first and last name into separate columns for the Email Blast Report only as suggested.

**Comment by amandagoyette** [comment]
Perfect Thanks!
