### ISSUE TITLE
Contact Report

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#23]
1. Can we call this Subscription Reports instead?
2. Can we remove website from the file and add in fax #? 
3. The state needs to be the abbreviation vs. full name for those in the US or it will not work for mailing (Example: Minnesota should be MN)

**Comment by anthonypartsconnect** [comment]
Hi Sagar, 

Please make these changes for Amanda.  #2 and #3 are changes within the report.  

Let me know if these make sense. 

Thank you.

**Comment by SagarPC** [comment]
We are done with all 3 changes and uploaded on stage. Please confirm our update.

**Comment by amandagoyette** [comment]
State is still showing up as the full name instead of abbreviation on these reports: 
![image](https://user-images.githubusercontent.com/26386841/48575343-52d36b00-e8d7-11e8-9a8b-a0e510cb470a.png)

**Comment by SagarPC** [comment]
@aharmening  We added a new column like State abbreviation and keep state full name as well, hope this will help you.

![image](https://user-images.githubusercontent.com/31076567/48625179-7fb97800-e9d4-11e8-87cb-ba691c301d65.png)

**Comment by amandagoyette** [comment]
Sagar, we can remove the column with the full state name like we are on other reports.

**Comment by SagarPC** [comment]
We removed the full state name column and kept only state code with State as a column name.

**Comment by amandagoyette** [comment]
Good to go
