### ISSUE TITLE
Export Report

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#24]
I need an option to export my full current list (This includes subscribers and those who haven't requested, but doesn't include expired), and an option to pull the full list including expired. 

It would be nice to be able to select which fields I want (Company, Contact, Alt Address, Delivery Address, City, State, Zip, and Country will always be included). If that's not an option always include phone, fax, and email too.

**Comment by stellaballa** [comment]
@SagarPC This request should go under the "Contact Report" Section. Change the title to "Subscriber Report".

**Comment by SagarPC** [comment]
We provided an option to select a column for the export report, where Company, Contact, Alt Address, Delivery Address, City, State, Zip, and Country default selected during export. 

![image](https://user-images.githubusercontent.com/31076567/48625356-f9e9fc80-e9d4-11e8-8c43-42512d3276a5.png)

**Comment by amandagoyette** [comment]
The export options are working thanks. 

This report should also include, or have the option to include, those with a lapsed subscription. 

You can also get rid of Column F and just call Column G State. I don't need both. 
![image](https://user-images.githubusercontent.com/26386841/48629936-88805e80-e980-11e8-883e-d12baf6bf7a5.png)

**Comment by stellaballa** [comment]
@SagarPC please confirm this has been updated

**Comment by SagarPC** [comment]
@aharmening : We are done with the change and uploaded on stage.

**Comment by stellaballa** [comment]
@aharmening please let us know if this looks good

**Comment by amandagoyette** [comment]
Please swap the alt address and delivery address.  
![image](https://user-images.githubusercontent.com/26386841/49538840-ecb48500-f891-11e8-9011-5a31d8e75759.png)

**Comment by amandagoyette** [comment]
The report itself is still not right though.  It should include everything: Current, Valid & Lapsed.  

I see an option to pull the expired/lapsed was added but that only pull those in that category.  This report needs to pull everyone regardless of their "status"

**Comment by stellaballa** [comment]
@aharmening  What if we add additional check box on top with ALL, Current, Valid & Lapsed, and have ALL Checked?

![screen shot 2018-12-05 at 11 35 28 am](https://user-images.githubusercontent.com/30122790/49539241-0ea60b80-f882-11e8-9261-448c9ce41b6b.png)

**Comment by amandagoyette** [comment]
@stellaballa that should work!

**Comment by stellaballa** [comment]
@SagarPC  please add the check box and make sure the Excel are export with the correct data.

**Comment by SagarPC** [comment]
@aharmening: We added  "All, Current, Expiring, Subscription Lapsed" 4 checkboxes for the selection. Please check our update and let us know if any change.

**Comment by stellaballa** [comment]
@aharmening I checked and looks like ALL and Current export the same data, I think this has to do with the database without expiring account or there's no expiration date on expired accounts.

**Comment by amandagoyette** [comment]
@stellaballa you're correct since the expired people haven't been imported they are close.  Current has 10918 records and All has 10923 records.  Thankfully a few people have expired that we imported so we can see the difference! 

Only change I have is it should be Current, Valid, and subscription lapsed.  Right now it's current, Expiring and Subscription Lapsed.  We have another report for expiring already.

**Comment by stellaballa** [comment]
@aharmening ok so we should update the check box to 1)ALL 2)Current 3)Valid 4)Subscription Lapsed

**Comment by amandagoyette** [comment]
@stellaballa yes, thanks!

**Comment by stellaballa** [comment]
@SagarPC  please update the check box

**Comment by SagarPC** [comment]
@stellaballa It's already uploaded on stage by yesterday.

**Comment by amandagoyette** [comment]
Looks good
