### ISSUE TITLE
Quarterly Mailing Report

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#25]
Remove Website, Phone & Email from this report. State needs to be abbreviated for US here too.

**Comment by stellaballa** [comment]
@SagarPC  This is for the Excel report.

**Comment by SagarPC** [comment]
removed column as suggested and display abbreviated code for US.

![image](https://user-images.githubusercontent.com/31076567/48549967-6098e880-e8f7-11e8-8139-fd5ce9800d6e.png)

**Comment by amandagoyette** [comment]
![image](https://user-images.githubusercontent.com/26386841/48575634-148a7b80-e8d8-11e8-8649-ff2614e6bc1e.png)
State not abbreviated

**Comment by SagarPC** [comment]
@aharmening We added a new column like State abbreviation and keep state full name as well, hope this will help you.

Also, there are numbers of the state where we don't have state code in the database and because of that, we are not able to show abbreviation code for those states. Please below file such list.

[Invalid States.xlsx](https://github.com/stellaballa/EP/files/2589503/Invalid.States.xlsx)

**Comment by amandagoyette** [comment]
Some I don't have abbreviations for and we can list the full state. From what I saw in the report I pulled for Issue #24 it appears the full state is listed where an abbreviation is unavailable as seen below:
![image](https://user-images.githubusercontent.com/26386841/48630162-312ebe00-e981-11e8-8f62-86388e13c32e.png)
As long as this logic is applied to all the reports we can get rid of the column showing the full state and just use the column shown above for the state as described in #24

**Comment by SagarPC** [comment]
We removed the full state name column and kept only state code with State as a column name.

**Comment by amandagoyette** [comment]
State column looks good. This report needs the Alt address too.

**Comment by SagarPC** [comment]
We added Alt address in the report Please see on stage (http://71.13.159.202/aeramms_stage/membership.aspx)

![image](https://user-images.githubusercontent.com/31076567/48773225-c49f2080-ecec-11e8-87e3-056f8a1503cf.png)

**Comment by amandagoyette** [comment]
@SagarPC can we put the Alt Address field before the delivery address on this report please. So it should go from Title to Alt Address then Delivery Address. Other than that it looks good!

**Comment by SagarPC** [comment]
@aharmening : It's uploaded on stage. Please confirm our update.

**Comment by amandagoyette** [comment]
Looks good
