### ISSUE TITLE
Fix Headers

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#26]
![image](https://user-images.githubusercontent.com/26386841/48289519-6c873500-e435-11e8-8341-faa820e64221.png)
I know we discussed this too, but putting it here:
Green should say Expiration Date
Blue "This Qtr" should be Expiring
Blue "Next Qtr" should be 1 Issue Left

**Comment by stellaballa** [comment]
@SagarPC please use this title for the columns and make sure you follow the logics in this ticket
https://github.com/stellaballa/EP/issues/7

**Comment by SagarPC** [comment]
Updated title as suggested.

![image](https://user-images.githubusercontent.com/31076567/48549391-ad7bbf80-e8f5-11e8-8821-a50d6e31b280.png)

**Comment by amandagoyette** [comment]
Good to go THanks!
