### ISSUE TITLE
Fix boxes for Selection

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#27]
![image](https://user-images.githubusercontent.com/26386841/48289687-f6370280-e435-11e8-8eb5-ab6dd8ef84af.png)
I have been thinking about these boxes.  Here's my thought:

The 1 issue left box we need to remove (Expiring) from the end. This pulls anyone with the 1 issue left column checked, which is correct.

Expiring should be its own option and include those marked in the Expiring column. I think that's what the Expired box pulls, if so just update the wording

Then we should have a 3rd option called Subscription Lapsed that includes those who have expired (were on the Expiring list the previous quarter and didn't renew) and the existing expired list I sent you. 

This one I may need to explain more, just let me know.

**Comment by stellaballa** [comment]
@SagarPC once we updated #7 this should make sense.
3 check boxes that matches #26

**Comment by stellaballa** [comment]
@aharmening  I think this has been updated.

**Comment by amandagoyette** [comment]
looks good
