### ISSUE TITLE
Update header on Edit Screen

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#28]
Please update the word "Updation" to just be Update
![image](https://user-images.githubusercontent.com/26386841/48383662-48815900-e6ac-11e8-9782-17ce895245f5.png)

**Comment by SagarPC** [comment]
Updated the word "Updation" to just be Update

![image](https://user-images.githubusercontent.com/31076567/48549470-e0be4e80-e8f5-11e8-8e14-91defa6a456b.png)

**Comment by amandagoyette** [comment]
Good to go thanks
