### ISSUE TITLE
Assign 1 Issue

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#29]
![image](https://user-images.githubusercontent.com/26386841/48527210-04c75480-e850-11e8-8246-dc2df7a0b7f7.png)
When using this function it should add them to the 1 issue left category, not the expiring category. 

![image](https://user-images.githubusercontent.com/26386841/48527305-54a61b80-e850-11e8-8e4f-8b7df33820b0.png)

**Comment by SagarPC** [comment]
updated the logic and now 1 issue left updating proper column.

**Comment by amandagoyette** [comment]
Tested and it's working
