### ISSUE TITLE
Printer Form should use the official one

### ISSUE THREAD

**Issue by stellaballa** [stellaballa/EP#3]
Here is a link to the official pdf, please replace it with the pdf version of form, because it makes no sense. 

http://www.engineprofessional.com/downloads/EPSUBSCRIBE.pdf
![screen shot 2018-11-05 at 12 17 27 pm](https://user-images.githubusercontent.com/30122790/48025244-b6031780-e0f7-11e8-94ab-32191f1ca999.png)

**Comment by SagarPC** [comment]
@stellaballa : Thanks for the official PDF. We used give pdf and now it's downloading official PDF only.
