### ISSUE TITLE
1 issue left email

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#30]
Can we update my title to just Circulation Specialist and add my last name so it says Amanda Harmening

![image](https://user-images.githubusercontent.com/26386841/48575753-6501d900-e8d8-11e8-9bd3-0bf0a279abe2.png)

**Comment by SagarPC** [comment]
updated information as suggested.

![image](https://user-images.githubusercontent.com/31076567/48625953-9fea3680-e9d6-11e8-87d3-735bf5daae28.png)

**Comment by stellaballa** [comment]
@aharmening please take a look and let us know if it has any issue.

**Comment by amandagoyette** [comment]
good to go.
