### ISSUE TITLE
Email set-up like in Prospect Tab

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#31]
In one of our meetings we discussed having the email set up so it opens an email, like in the Prospects tab. Can we make that change?

**Comment by stellaballa** [comment]
@aharmening sorry I don't recall discussion on the email form. Would you like us to add the function just like the Prospects tab, when you click on the user email it open a email form? Is there any content you would like to populate inside the form? 
![screen shot 2018-11-15 at 1 33 01 pm](https://user-images.githubusercontent.com/30122790/48583087-21f53500-e8db-11e8-9fd1-a7821dce18bb.png)

**Comment by amandagoyette** [comment]
@stellaballa I'm going to let @kbt1 answer on this one as it's a function she's requested so she can email them trying to get them to become members.

**Comment by stellaballa** [comment]
I see, @kbt1 please let us know.

**Comment by kbt1** [comment]
That would be perfect where i can enter something in the subject line and in the body and add attachments.

**Comment by stellaballa** [comment]
@SagarPC please add this function for the email.

**Comment by SagarPC** [comment]
added new function to send email for the EP tab

![image](https://user-images.githubusercontent.com/31076567/48626084-f3f51b00-e9d6-11e8-98ad-ed420aca6d5f.png)

**Comment by amandagoyette** [comment]
File and subject came through but the message did not:
![image](https://user-images.githubusercontent.com/26386841/48632494-a781ef00-e986-11e8-9129-58832c499bdd.png)

**Comment by kbt1** [comment]
When I tested the email link, the body of the email didnt come through like Amandas comment above and If I am the one sending the email, it should come up From/Reply to Karen@aera.org and it comes up Amanda@aera.org.
This email link should work just like the Prospect Tab email link

**Comment by SagarPC** [comment]
@kbt1 : The email body should work now. Please check and confirm our update.

Also, let me know which email id we need to add as "From/Reply To".

**Comment by amandagoyette** [comment]
Body of the email is working.  I am going to leave this open so Karen can get back to you on the reply to. She is out this week.  If it helps, I believe, the prospect tab is tied to whoever is logged in. So, for me it shows amanda@aera.org, Karen it shows karen@aera.org, Steve it shows steve@aera.org, etc.

**Comment by stellaballa** [comment]
@kbt1 please check and confirm.

**Comment by amandagoyette** [comment]
@kbt1 please test this one.  I know one function you wanted was that the reply to defaults to user.  I cannot test this as it was defaulting to me regardless.  Thanks!

**Comment by kbt1** [comment]
Works perfect!
