### ISSUE TITLE
Ability to sort by different columns

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#32]
Is it possible to have the option to sort by columns like we do in membership. The ones with an X above them are the columns we'd use that for. 
![image](https://user-images.githubusercontent.com/26386841/48577149-0c343f80-e8dc-11e8-8bd3-19ff17b0f7b9.png)

**Comment by stellaballa** [comment]
@aharmening @SagarPC it might be hard to add a spreadsheet style sorting function. What if we add dropdown on top to help you filter out the content? Can you let us know for each column, how would you like the information to be sorted?

**Comment by amandagoyette** [comment]
Filter could work. when I'm looking at a group I could see myself looking at who has a requested date and who doesn't, who has an email address or doesn't, who has a phone number or doesn't. 

The company, contact, state and country would be more if I'm searching a name, city, company, etc. and need to find someone from there.  
       Example: If I search for Springfield it will pull up results in CO, IL, KY, LA, MA, MO, NE, OH, OR, PA, TN & VA. It would be nice to be able to some how sort the states so they're in order or filter down to the one I need rather than flipping through pages of results.

Does that help see the logic @stellaballa ?

**Comment by stellaballa** [comment]
Thanks @aharmening let me think about this and propose a solution.

**Comment by stellaballa** [comment]
@aharmening I added 2 filters and change the account type to a filter. 
You can use the account type filter to sort the list or use the text search for a name. And the other 2 filter will sort the content. 

![ep-filters](https://user-images.githubusercontent.com/30122790/48588920-eca61280-e8ed-11e8-880b-c72ea4e3b2d6.png)

**Comment by amandagoyette** [comment]
@stellaballa that looks like it should work. Let us know when it's live in the staging site and we'll test it.

**Comment by SagarPC** [comment]
@aharmening: We have implemented this new search and order by function and uploaded on stage.

Please check and confirm our update.

**Comment by amandagoyette** [comment]
Can we add a filter for those with a fax number? 
We don't need the filter for those without a phone number. 

I'll Karen's input on this when she's back too.

**Comment by SagarPC** [comment]
We added "With Fax" in the sort by the filter. and We removed "No Phone" from the sort by the filter. Please see on stage (http://71.13.159.202/aeramms_stage/membership.aspx)

![image](https://user-images.githubusercontent.com/31076567/48773283-f0220b00-ecec-11e8-9fec-8a78983cfab7.png)

**Comment by amandagoyette** [comment]
Fax option looks good. I'm leaving this open til Karen and I have a chance to talk about it.

**Comment by stellaballa** [comment]
@kbt1  can you please check this and close the ticket if it looks good?

**Comment by amandagoyette** [comment]
@kbt1 this looks good to me.  I'm going to close it.
