### ISSUE TITLE
Email confirmation to me

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#33]
I know we talked about this before. I'm just making sure it doesn't get forgotten.

I should receive some sort of a confirmation when someone requests a subscription or renews their subscription. I'm required to have the paper trail for our end goal of mailing periodical.  Below is what I currently receive:

![image](https://user-images.githubusercontent.com/26386841/48581544-c1202980-e8e7-11e8-8e47-50e1e4a99aa7.png)

**Comment by stellaballa** [comment]
@aharmening Yes
@SagarPC please make sure an email notification is sent to Amanda once someone submit a subscription form. If you could also add a link directly to the user detail window that would be great.

**Comment by SagarPC** [comment]
@aharmening: You will get email like below with the Status field. That will help you to identify user action. It's updated on stage so now onward you will get email from the stage. Once you done with the testing on stage please let me know, I will stop stage website admin email to you. Otherwise it will create confustion to you with stage and live email notification.

![image](https://user-images.githubusercontent.com/31076567/48626476-f3a94f80-e9d7-11e8-80b5-fbdf9aeb5066.png)

**Comment by amandagoyette** [comment]
Can we change the text to say:

This email is to notify you that Jagish Sagar has requested a subscription to Engine Professional Magazine.

Also, we can get rid of the footer since it's just an internal note it doesn't need the info on how to contact us and that it's an intl publication

**Comment by amandagoyette** [comment]
The version for "YES" should say: 
This email is to notify you that **Amanda h** has renewed their subscription to Engine Professional Magazine. 
![image](https://user-images.githubusercontent.com/26386841/48632858-a0a7ac00-e987-11e8-8534-f55b6be6b557.png)

**Comment by amandagoyette** [comment]
For the status I don't need to know if it's a renewal or new I can figure that out from the text above. It should reflect which box they check: Yes vs. No

**Comment by amandagoyette** [comment]
The version for those who select "No" should read:
This email is to notify you that **Manda p** has cancelled their subscription to Engine Professional Magazine. 
![image](https://user-images.githubusercontent.com/26386841/48635839-e2882080-e98e-11e8-84e6-7fc68c7cb07a.png)

**Comment by stellaballa** [comment]
@SagarPC can you confirm you have updated this?

**Comment by SagarPC** [comment]
@aharmening: We updated email content as suggested and uploaded on stage.

**Comment by amandagoyette** [comment]
Looks good thanks!
