### ISSUE TITLE
Yes vs. No vs. neither on subscription form

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#34]
On the form when they go to renew some people forget to select a box:
![image](https://user-images.githubusercontent.com/26386841/48633380-d0a37f00-e988-11e8-8d53-aa6e91af8912.png)
If neither is checked we either need something to tell them they're required to check one or it needs to come back a blank or incomplete. Right now it defaults to no and we can't have that happen as 99% of the time they mean to click yes and we don't want them to fall off the list. 
![image](https://user-images.githubusercontent.com/26386841/48635308-680ad100-e98d-11e8-9d90-f96caa9ac4f0.png)

**Comment by kbt1** [comment]
I would say have it default to Yes.

**Comment by amandagoyette** [comment]
@kbt1 I can't do that as it could cause me problems with getting Periodical status

**Comment by kbt1** [comment]
so nothing should be default and the subscriber must check a box? makes sense.

**Comment by amandagoyette** [comment]
correct

**Comment by SagarPC** [comment]
@aharmening: We did this change and uploaded on stage.

http://71.13.159.202/aerastage/EngineProfessional.aspx

**Comment by amandagoyette** [comment]
Looks good. Thanks!
