### ISSUE TITLE
Typo in Reports

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#35]
Please fix the word contact in the reports
![image](https://user-images.githubusercontent.com/26386841/48744269-36fbfc00-ec2c-11e8-9145-4b854a892221.png)

**Comment by SagarPC** [comment]
We have corrected "Contact" Words in the reports. Please see on stage (http://71.13.159.202/aeramms_stage/membership.aspx)

**Quarterly Mailing Report**
![image](https://user-images.githubusercontent.com/31076567/48773467-74748e00-eced-11e8-810d-45630a710732.png)

**Subscriber Report**
![image](https://user-images.githubusercontent.com/31076567/48773473-7b030580-eced-11e8-87df-d1c247cc1c97.png)

**Export Report**
![image](https://user-images.githubusercontent.com/31076567/48773477-7e968c80-eced-11e8-9761-0c957a5c42f6.png)

**Comment by amandagoyette** [comment]
Looks good thanks!
