### ISSUE TITLE
Update Decline Email

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#37]
Can we update the text to read: 

![image](https://user-images.githubusercontent.com/26386841/48746486-3b78e280-ec35-11e8-8e01-bc2613d63b5e.png)

This email is to notify you that your subscription to Engine Professional Magazine has been cancelled. We are sorry to see you go. If you wish to resubscribe please visit www.engineprofessional.com/subscribe.

**Comment by SagarPC** [comment]
The given link www.engineprofessional.com/subscribe is not working.

**Comment by stellaballa** [comment]
@sagarPC try this link http://www.engineprofessional.com/subscribe.html

**Comment by SagarPC** [comment]
We have updated text as per request, and also updated Link subscribe link which was not working. Please see on stage (http://71.13.159.202/aeramms_stage/membership.aspx)

![image](https://user-images.githubusercontent.com/31076567/48773776-65daa680-ecee-11e8-85e8-d9de610e3f3d.png)

**Comment by amandagoyette** [comment]
http://www.engineprofessional.com/subscribe.html try this

Amanda Harmening
AERA Engine Builders Association

________________________________

**Comment by SagarPC** [comment]
@aharmening: We already used that and uploaded on stage. Please check and confirmed.

**Comment by amandagoyette** [comment]
@SagarPC I saw that after I sent it. I will test everything today. Thanks!

**Comment by amandagoyette** [comment]
Looks good thanks!
