### ISSUE TITLE
Phone Number

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#38]
I noticed on the phone column is really wide. I think we can make it smaller without losing anything I can update my records to lose the extra characters. My longest phone number without an extension is 114971162769838 and my longest with an extension is 4192248000X22327

Also, I noticed there's no standard format to the phone number field. Some seem to be with the - others have ( ) and some of the foreign have the +. I also noticed the extensions listed, but I cannot edit the extra characters/numbers without losing them. Nor can I add more than a standard 10 digit phone number.  I'm not sure what the options are, I want to make sure I have everything in the right place/format before we import the list so it is all correct on import. 

@stellaballa I'd appreciate your two cents on this. I think Membership we just do a 10-digit phone number. I'm ok sticking with the same format if you think that's best. If we go that route maybe we can add the fax # to the main page since both will only need 10 characters? 

![image](https://user-images.githubusercontent.com/26386841/48798309-fbb00a80-ecc9-11e8-8787-e8acaf39d492.png)

**Comment by stellaballa** [comment]
@aharmening & @SagarPC 
1) We should standardize all phone number formatting to "-" XXX-XXX-XXXX for international number we can do +XX-XXX-XXXXXX 
2) Extension, I think we should have a separate field for extension. 
![screen shot 2018-11-20 at 1 49 35 pm](https://user-images.githubusercontent.com/30122790/48805212-a117ae00-eccb-11e8-8a68-74dec19a332f.png)
3) The preview of the # with extension should be 000-000-0000 x 0000
4) @aharmening do you need fax# to show up? We can add the column, there should be enough room.

**Comment by amandagoyette** [comment]
I will make sure everything is set up with that format on my end for international vs. foreign so we have an easy import when the time comes.

As far as the fax, yes, it would be helpful to have that on there if there is room.

**Comment by stellaballa** [comment]
@aharmening I think @SagarPC can update the formatting on his end, let's wait for his respond.

**Comment by SagarPC** [comment]
@stellaballa ,

We worked on this task, I do have some questions.
1) what is the max length for the extension?
2) need to add the extension in the signup form.
 http://71.13.159.202/aeramms_stage/membership.aspx
3) Inside requirement, you said, "international number we can do +XX-XXX-XXXXXX"
=> We have only one textbox, Inside one textbox we can't use multiple placeholders. We can decide based on Country selection but the problem is the country we have after phone. Please suggest.
4) Should we need to add ext. inside fax?

**Comment by amandagoyette** [comment]
I'd say 5 characters will be sufficient. That's the longest I have currently
 No extension needed on fax.

**Comment by SagarPC** [comment]
1.	Should I add the extension inside the signup form?  
                 http://71.13.159.202/aerastage/engineProfessional.aspx
	2.	Inside requirement, you said, "international number we can do +XX-XXX-XXXXXX" => Please review my attached document
	3.	We have phone numbers with greater than 11 digits, How we have to display those numbers inside the system, Please refer attached document suggestion_issue_38.docx, Where I added suggestions about Country dropdown placement.
[suggestion_issue_38.docx](https://github.com/stellaballa/EP/files/2615917/suggestion_issue_38.docx)

**Comment by amandagoyette** [comment]
1. Offering the extension in the signup form is a good idea, yes.
2. Your document makes sense to me. I think that is good logic.
3. I think the longest number is 15 digits, so as long as there is the extension field as shown in your document we will have 2 options on our end, we can either put the extra digits there or we can list the phone number in the comments (or we can do both).

**Comment by SagarPC** [comment]
We had completed most of the changes inside our local. We are ready to move our changes on stage. We will do once we have a normal stage server.

> I think the longest number is 15 digits, so as long as there is the extension field as shown in your document we will have 2 options on our end, we can either put the extra digits there or we can list the phone number in the comments (or we can do both).
=> We will add all invalid phone numbers into the comment (Note). We will consider below scenarios for invalid phone number
1) Phone number format doesn't match with the country 
2) Don't have the country
=> If the phone number format is as per country's defined format (Example USA => 10 digits, International 11 digits) then we won't clear textbox value in edit case, else we clear the value. When we clear the value we will give a message about the user can refer old phone numbers into the note. Please check the attached document.
[Implementation_Issue_38.docx](https://github.com/stellaballa/EP/files/2620422/Implementation_Issue_38.docx)

**Comment by SagarPC** [comment]
@stellaballa: We are done with all the above changes on stage. You can refer my last comment and attached document for that.

**Comment by amandagoyette** [comment]
looks good!
