### ISSUE TITLE
Latest Database

### ISSUE THREAD

**Issue by stellaballa** [stellaballa/EP#39]
@aharmening  can you post latest Excel with all account for EP on basecamp? 
https://basecamp.com/2423539/projects/15213494/messages/81989982

**Comment by amandagoyette** [comment]
@stellaballa do you need me to split out current vs. valid vs. expired or just send it as is?

**Comment by stellaballa** [comment]
As long as there's column identifying they are current and valid and expired, sagar can import that data.

**Comment by amandagoyette** [comment]
@stellaballa it's uploaded. If there are questions let me know. I will be checking my email the next couple days.

**Comment by stellaballa** [comment]
Thanks! @SagarPC please import the latest data into EP.

**Comment by SagarPC** [comment]
@stellaballa:

We imported the latest data on stage. We considered "Current & Valid" and "Current, Not Valid" sheets from the given excel file. We not considered "Expired" sheet from that excel, please confirm.

**Comment by amandagoyette** [comment]
@stellaballa The current and valid both appear correct.  In regard to Sagar's question the Expired sheet will need to be imported in before we go live.  Those are the "subscription lapsed" people.

**Comment by stellaballa** [comment]
Thanks @aharmening Do we have the latest Expired data? Or you will have to provide.

**Comment by amandagoyette** [comment]
@stellaballa I will have to get you updated info for a 3 parts (Curent & Valid, Curent, Not Valid, and Lapsed/Expired) as it gets updated at least weekly if not more often.

**Comment by stellaballa** [comment]
@aharmening in that case, we should schedule the time to launch this with the latest data, and once launch you can use the system to do update.

**Comment by amandagoyette** [comment]
@stellaballa I agree.  If we get all the testing/updates wrapped up this week maybe we can aim for Monday or Tuesday? That gives me the rest of the week to clean up everything and then once I send them I will not edit until we are live.

**Comment by stellaballa** [comment]
@SagarPC  Let's do a final round of QA on the staging server this week and plan to go live next Monday evening. And have the team stand by on Tuesday morning to make sure everything is working correctly. 

@aharmening please send us the final data end of Monday.

**Comment by amandagoyette** [comment]
@stellaballa will do!

**Comment by SagarPC** [comment]
@stellaballa: We just looked into the Expired sheet to load data but notice there is a blank expiration date and also there is no date of request.

https://basecamp.com/2423539/projects/15213494/messages/81989982

If the user having blank expiration date then we are considering that user is the current user as per current logic. Please let us know how can we move forward with this sheet.

If we set past month date as the expiration date for those users where we have blank expiration date only for the "Expired" sheet then it will resolve the issue.

**Comment by stellaballa** [comment]
@aharmening is it possible to add a expiration date to the expired account? Right now the system will confused with expired account as current if they don't have an expiration date.

**Comment by amandagoyette** [comment]
@stellaballa I've thought it through and I think that will work.  I will make sure all those in the expired tab have an expiration date before I send it Monday.

**Comment by stellaballa** [comment]
Great! @aharmening

**Comment by stellaballa** [comment]
@SagarPC  we will add expiration date, and @aharmening will provide the date in the latest data file she will be sending over on Monday before launch.

**Comment by amandagoyette** [comment]
@stellaballa should the extension have its own column on my spreadsheet? I'm working on finishing up the Subscription Lapsed tab for you guys before moving on to the other two, and right now it is in with the phone number like this: 
![image](https://user-images.githubusercontent.com/26386841/49680955-1a4f2900-fa60-11e8-8ee1-8a97be402353.png)

**Comment by stellaballa** [comment]
@aharmening  I think it would be helpful to have it on a separate column. You can remove the X or any characters that's not the extension.

**Comment by amandagoyette** [comment]
@stellaballa will do. It's an easy fix for me.  Thanks!

**Comment by amandagoyette** [comment]
@stellaballa @SagarPC the latest file has been loaded to Base Camp

**Comment by SagarPC** [comment]
uploaded the latest file to live site and posted my comment in basecamp about invalid record that we can't process.

**Comment by amandagoyette** [comment]
Fixed invalid record and uploaded it to basecamp.  Sorry I missed that one somehow!

**Comment by SagarPC** [comment]
@aharmening : We updated that record to the live.

**Comment by amandagoyette** [comment]
@SagarPC thanks! 
@stellaballa not sure if we still need this open or not. Can close as far as I'm concerned.
