### ISSUE TITLE
Move EP Tab

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#40]
Can we move the EP tab so it is right before the EP Reports? Steve, Karen, and I all feel this will make navigating easier.  Thanks!
![image](https://user-images.githubusercontent.com/26386841/49090773-0582c200-f224-11e8-9377-9739ec508c7b.png)

**Comment by stellaballa** [comment]
@aharmening  please take a look

**Comment by amandagoyette** [comment]
Good to go
