### ISSUE TITLE
Expiring

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#41]
Is it possible to only have the selection change quarterly if they don't renew?  As I'm looking I see that these are "Subscription Lapsed" instead of "Expiring" because the date has passed.  
![image](https://user-images.githubusercontent.com/26386841/49614548-468b7c80-f970-11e8-8233-e93d1893d970.png)

Vs. these are still "Expiring" because the date is yet to come:
![image](https://user-images.githubusercontent.com/26386841/49614589-5acf7980-f970-11e8-8c12-af23ebe3df69.png)

What I'm afraid of, is typically we mail this quarter's mailing in October.  I try to wait 2 weeks at least before sending out notifications as some people will send a card in on their own.  By the time I do my mailing, I am worried that the first month will no longer be on my expiring list so they will not get their emails or postcard.  

Does that make sense?

**Comment by stellaballa** [comment]
@aharmening would you like to count the expiration date as 3 month after the actual expiration date? And during the 3 month that acc would consider lapses?

**Comment by amandagoyette** [comment]
@stellaballa I think maybe you and I should talk this one out and decide if it's best to leave it alone or if there is a better way.  Do you have time for a quick call today?

**Comment by amandagoyette** [comment]
@stellaballa This is the section of reports I'm talking about:
![image](https://user-images.githubusercontent.com/26386841/49660189-9cf9c900-fa0b-11e8-93dd-8eb90f32c131.png)
If it's possible to select a date range for the expiring report I think that would solve our issue.

**Comment by stellaballa** [comment]
@SagarPC Can we move Expiring as the last option, and add a From: DD/MM/YY  To: DD/MM/YY  option so Amanda can select accounts that are expiring between a period (example, between 03/15/2019 - 06/30/2019)

**Comment by SagarPC** [comment]
@stellaballa: We added exp. date on expiring selection. Please check and confirm it's working as expected.

![image](https://user-images.githubusercontent.com/31076567/49711160-d9bffd00-fc63-11e8-9802-2b05a0a30e25.png)

**Comment by amandagoyette** [comment]
Sagar when I put in this date range (4th quarter) it only gives me 12/11-12/31 
![image](https://user-images.githubusercontent.com/26386841/49745886-98305180-fc65-11e8-8cb0-db638003f289.png)
I tried checking subscription lapsed in addition to expiring and then got all expired dating back to 2015.  I need some way I can pull all expiring subscribers for the current quarter (10/1-12/31)

**Comment by SagarPC** [comment]
@aharmening: Now it's exporting data from 1st OCT 2018 to 31st DEC 2018. It's uploaded on stage and live both.

**Comment by amandagoyette** [comment]
Tested and it is working.  Thanks Sagar
