### ISSUE TITLE
List

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#42]
Please add Big River to the list section:
![image](https://user-images.githubusercontent.com/26386841/49673303-9e3eec00-fa33-11e8-819a-958fe60c9daf.png)

**Comment by SagarPC** [comment]
added Big River to the list.

![image](https://user-images.githubusercontent.com/31076567/49711239-4804bf80-fc64-11e8-86f4-fef263f34e25.png)

**Comment by amandagoyette** [comment]
Thanks!
