### ISSUE TITLE
Type

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#43]
Add Mail to Type
![image](https://user-images.githubusercontent.com/26386841/49673698-f6c2b900-fa34-11e8-94f4-3efbc5fc246a.png)

**Comment by stellaballa** [comment]
@SagarPC  Please add.

**Comment by SagarPC** [comment]
added Mail to Type dropdown option.

![image](https://user-images.githubusercontent.com/31076567/49711297-a92c9300-fc64-11e8-964a-72d48b1a3618.png)

**Comment by amandagoyette** [comment]
Thanks!
