### ISSUE TITLE
Record will not update

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#44]
I'm entering some requests into the live site now that we're up and this one will not update:
![image](https://user-images.githubusercontent.com/26386841/49812657-874a1380-fd2b-11e8-919a-129b8896d0a3.png)

The other 3 I did worked perfectly, but this one I tried updating the start date to 12/7/18 and marking it as a valid request. When I click update it tells me it updated the information, but nothing changes.

**Comment by stellaballa** [comment]
@SagarPC  please look into this.

**Comment by SagarPC** [comment]
There is an issue with **'s** character.  We resolved this issue on stage and live both.

**Comment by amandagoyette** [comment]
record updated, so I know we're set.  Thanks!
