### ISSUE TITLE
Tweak wording on pop-up

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#45]
Can we change this to say Thank You instead of e-Thank You

![image](https://user-images.githubusercontent.com/26386841/49965135-f23d4b00-fee1-11e8-8641-e47d876f4aee.png)

**Comment by stellaballa** [comment]
@SagarPC please update.

**Comment by SagarPC** [comment]
We updated message on stage and live both.

**Comment by stellaballa** [comment]
@aharmening  please check

**Comment by amandagoyette** [comment]
good to go thanks!
