### ISSUE TITLE
Notification email

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#46]
Maria has updated the request link to reflect the link you provided.  I tested it, and I am not receiving the confirmation email notifying me that someone subscribed.  Please advise.

**Comment by amandagoyette** [comment]
It appears I'm not getting any of the notification emails if that helps.  I just tested a change info and didn't get it either.

**Comment by stellaballa** [comment]
@aharmening  we will look into this.

**Comment by amandagoyette** [comment]
Thanks Stella!

**Comment by SagarPC** [comment]
@aharmening: Please check now, I just restarted AERA MMS and Prosis Pro application.

**Comment by amandagoyette** [comment]
Good to go
