### ISSUE TITLE
Request Date

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#47]
I sent Dave a renewal form since he's on my list and hadn't subscribed as I wanted to make sure that emails were going out okay.  I noticed when I checked later that it updated his expiration date, but didn't mark his request date:
![image](https://user-images.githubusercontent.com/26386841/50110047-e8c42380-01fe-11e9-92bd-f823adff8bdc.png)
The Requested Date should be 12/17/18

I asked Rob to test it for me since he had a date in their previously to see if it was only those who hadn't subscribed, but it was the same thing:
![image](https://user-images.githubusercontent.com/26386841/50110132-1c9f4900-01ff-11e9-873b-84fbdf29227c.png)
Rob's should have updated from 9/17/18 to 12/17/18.

**Comment by SagarPC** [comment]
@aharmening: Now, we updated requested on subscription with the update and accept subscription only. If user decline subscription we are not updating request date as of now. please let us know if we need to update request date on decline subscription as well.

**Comment by amandagoyette** [comment]
@SagarPC no, the decline does not need to be updated.  Thanks.  I'm testing today and will close out the ticket once I've confirmed it is all working.

**Comment by amandagoyette** [comment]
good to go
