### ISSUE TITLE
Printing emails

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#48]
When I get the emails they look right:
![image](https://user-images.githubusercontent.com/26386841/50178636-b122ad80-02ca-11e9-891e-81a27e1b8aa5.png)
but when I go to print the logo prints funny like it has been enlarged.  It's just being used internally so it's not a huge deal, but I'm not sure why it is happening:
![image](https://user-images.githubusercontent.com/26386841/50178750-f810a300-02ca-11e9-9797-bf1a6df8b572.png)

Any ideas?

**Comment by stellaballa** [comment]
@SagarPC  please check

**Comment by SagarPC** [comment]
We looked with the gmail and microsoft mail box and it's working fine with both. Please let me know which email box you are using to print email.

**Comment by amandagoyette** [comment]
I am printing from outlook

Amanda Harmening
AERA Engine Builders Association

________________________________

**Comment by stellaballa** [comment]
@SagarPC  can you try it with outlook and see if you can produce the same bug?

**Comment by SagarPC** [comment]
@aharmening : We checked with the outlook as well and it's working fine for us. I think you are using old version of outlook. 

However we did changes in email header logo format, so please check newly received email after this date and provide your feedback on this.

**Comment by amandagoyette** [comment]
I'm closing this as it's an issue on my end
