### ISSUE TITLE
screen view

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#49]
Is it possible to adjust this so I don't have to scroll to save every time I'm editing?  It's fine on my larger monitor, but when I'm working off my laptop I have to scroll.

![image](https://user-images.githubusercontent.com/26386841/50292931-08925c00-0438-11e9-8fb5-c0e155215e41.png)

**Comment by stellaballa** [comment]
@SagarPC please fix

**Comment by SagarPC** [comment]
We set hight of the view window as much as we can. Please check and let me know if this will work or not.

**Comment by amandagoyette** [comment]
that works thanks!
