### ISSUE TITLE
Thank you screen

### ISSUE THREAD

**Issue by stellaballa** [stellaballa/EP#5]
Please make the confirmation screen on the same page and not a pop up screen, and don't redirect them to the Prosis Pro login page. 

[Form-UpdateInfo.pdf](https://github.com/stellaballa/EP/files/2550783/Form-UpdateInfo.pdf)

**Comment by SagarPC** [comment]
@stellaballa : shown Thank you message on the same screen.

http://71.13.159.202/aerastage/EngineProfessional.aspx
