### ISSUE TITLE
Start date

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#50]
Can we set the start date to default to the current date when we click on it:
![image](https://user-images.githubusercontent.com/26386841/50293590-9458b800-0439-11e9-8cb7-863489545ad5.png)

Or

Set it up so that if we manually type the date it updates the Expiration date too:
![image](https://user-images.githubusercontent.com/26386841/50293892-442e2580-043a-11e9-9659-8e6326f6f596.png)

**Comment by stellaballa** [comment]
@SagarPC  please update

**Comment by SagarPC** [comment]
@aharmening: 

We taken action on below point and now it will update expiration date. Please check and confirm our update.
+++++++++++++++++++++
Set it up so that if we manually type the date it updates the Expiration date too:
+++++++++++++++++++++

**Comment by amandagoyette** [comment]
It's working thanks!
