### ISSUE TITLE
List/Type

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#51]
On the Preview Screen these appear to be completed:
![image](https://user-images.githubusercontent.com/26386841/50359748-68b1fc80-0523-11e9-89d9-acdcdc4573f1.png)

When I open to edit they are gone:
![image](https://user-images.githubusercontent.com/26386841/50359778-7f585380-0523-11e9-94d7-0bef23209c68.png)

Then if I make changes and save it loses them completely:
![image](https://user-images.githubusercontent.com/26386841/50359834-b169b580-0523-11e9-9f19-dc950583837b.png)

**Comment by amandagoyette** [comment]
Note: Some it keeps.  So far I've noticed MASTER and BIG RIVER for sure getting removed under "List" 
![image](https://user-images.githubusercontent.com/26386841/50360036-54223400-0524-11e9-92e4-ea638c56aed5.png)

**Comment by SagarPC** [comment]
@aharmening : We fixed this issue and not all the option available in drop down will keep selected in edit case not get blank. 

However, I want to inform you like an option which not available in the dropdown that comes as List then it will not be selected.

Example: "PERA" as list option is not a valid case, see below it's showing text in view case but when you click on Edit it will be gone.

![image](https://user-images.githubusercontent.com/31076567/50397565-60fa8e00-0797-11e9-8f53-5cac496aa5cb.png)

I attached all those members who have invalid List and Type value for reference. Please refer attached excel file for that.

[Invalid_List.xlsx](https://github.com/stellaballa/EP/files/2707098/Invalid_List.xlsx)
[Invalid_Type.xlsx](https://github.com/stellaballa/EP/files/2707099/Invalid_Type.xlsx)

**Comment by amandagoyette** [comment]
Thanks Sagar.  Yes, I tried to clean up the codes I was getting rid of, but know I missed some.  I'll pull your lists so I can get those cleaned up.
