### ISSUE TITLE
Valid Requests

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#52]
I filtered the valid requests and noticed the numbers were much larger than my excel file.  It appears the valid filter includes expired requests, but it shouldn't.  A request is no longer valid if it's expired.  Please let me know if you need more of an explanation.
![image](https://user-images.githubusercontent.com/26386841/50450616-a84a6100-08f4-11e9-96bf-3c835c94c7f3.png)

**Comment by stellaballa** [comment]
@SagarPC  please take a look

**Comment by SagarPC** [comment]
We did change and now valid with no longer considering expired user. We did this change in report export and EP listing both. Please verify our update on live.

**Comment by amandagoyette** [comment]
looks good
