### ISSUE TITLE
Phone Number

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#53]
Is there a way to set Canada up as the same format as the US?  We get Canada numbers in the same format (xxx-xxx-xxxx), so I'm unable to enter any of them.

**Comment by stellaballa** [comment]
@SagarPC  please look into this.

**Comment by SagarPC** [comment]
@aharmening  We did this change and now you can add Canada number to the same format as the USA.

**Comment by amandagoyette** [comment]
Confirmed it works.  Thanks!
