### ISSUE TITLE
Issue Editing Specific Record in EP Tab of MMS

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#54]
![Fuad](https://user-images.githubusercontent.com/26386841/57161710-d7487600-6db1-11e9-83a7-109048c51e03.jpg)
Can you have your team look into this record for me.  He’s on my EP list and I can get this far, but when I click edit nothing happens.  I had Karen try searching him from her machine and she gets stuck in the same place.  I can open others just fine, so I think it’s something specifically with Fuad’s record.

**Comment by SagarPC** [comment]
I looked into this issue and found an issue with the invalid State information for that member. I just removed invalid information and now it's working. That invalid information added during the initial setup of the EP tab, we loaded data from the EXCEL to AERA MMS system.
Now, it's working.

**Comment by amandagoyette** [comment]
Thank you!

Amanda Harmening
AERA Engine Builders Association

________________________________
