### ISSUE TITLE
Required fields on Subscription form

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#55]
Can we update the subscription form so the State & Zipcode are not required?  Some countries don't have this information.  Thanks! 
![image](https://user-images.githubusercontent.com/26386841/58188533-62fd4600-7c7e-11e9-84eb-4e3b77494f59.png)

**Comment by stellaballa** [comment]
@aharmening  will do!

**Comment by SagarPC** [comment]
@aharmening   We updated code and set State & Zipcode as optional.

https://www.prosispro.com/engineprofessional.aspx
