### ISSUE TITLE
Valid Request

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#56]
When you update an expired request the "Valid Request" option isn't updated.  the below example was expired, and when I updated the start date to reflect 7/19/19 the "no" option remained selected when it should have switched to "yes".  I tried to save the updates and it still remained at "no".  Please fix so that anything with a start date in the 3 year window defaults to "yes"
![image](https://user-images.githubusercontent.com/26386841/61824764-6cdd2a00-ae24-11e9-81d1-0e5b7fbcbe9c.png)

**Comment by stellaballa** [comment]
Thanks @aharmening  we will look into this.

**Comment by SagarPC** [comment]
@aharmening We addressed this issue and not Valid/Invalid default selection will be changed based on exp. date update. If exp. the date is the future date then it will show as Valid and if exp. the date is the past date then it will show invalid.

**Comment by amandagoyette** [comment]
thanks @SagarPC is there anyway to automatically update everything in the system?  There are expired contacts right now that still say yes such as this one: 
![image](https://user-images.githubusercontent.com/26386841/61894619-76bf6580-aed6-11e9-93c1-eaf8dc0d769d.png)

**Comment by SagarPC** [comment]
@aharmening  We can do this automated, for this, we need to create on daemon application which executes daily at your night time. That application will check and update status for the expired EP members. 

Please let me know if it's work.

**Comment by stellaballa** [comment]
@aharmening  please let us know if this would work. @SagarPC  people go ahead and work on it once Amada confirms.

**Comment by SagarPC** [comment]
@aharmening can you please look into the solution which I provided? Also, give us confirmation so we can start work on this.

Regards,

**Comment by amandagoyette** [comment]
@SagarPC sorry for the delay I was out last week and have been playing catch up.  We really don't need it updated daily.  As long as it's done weekly we'll be good not sure if it makes a difference on your end.  @stellaballa mentioned the system may run a little slower while this process is going, so I was thinking maybe we could do it Saturday nights to minimize interruptions? Let me know.

Thanks!

**Comment by SagarPC** [comment]
We can set up this process weekly at the suggested time.

**Comment by stellaballa** [comment]
@SagarPC  please go ahead with this.

**Comment by SagarPC** [comment]
@aharmening I am working on the script and during this work, I notice below things where I need your feedback.

1) There are many numbers of active (_future expiration date_) EP member with **Invalid** Status.
=> When we execute script all those members become **Valid**, is that correct behavior. Please see attached file for the list of those members. 
[ep-active-invalid-member-list.xlsx](https://github.com/stellaballa/EP/files/3466273/ep-active-invalid-member-list.xlsx)

2) There are many numbers of expired (_past expiration date_) EP member with **Valid** Status.
=> When we execute script all those members become **InValid**, is that correct behavior. Please see attached file for the list of those members. 
[ep-expired-valid-member-list.xlsx](https://github.com/stellaballa/EP/files/3466274/ep-expired-valid-member-list.xlsx)

**Comment by amandagoyette** [comment]
@SagarPC Not sure where column A is coming from as the EP list doesn't have ID Numbers.

1. Only those with a start date should be active and I've highlighted those in the attached list.  The others are not Valid as they do not have a start date. I have to add an end date in order to get them into the rotation for 1 issue left and expired. 
[ep-active-invalid-member-list.xlsx](https://github.com/stellaballa/EP/files/3468531/ep-active-invalid-member-list.xlsx)

2. Yes, any of those that are expired should be marked invalid.  Once their subscription lapses they are no longer valid unless they renew.

**Comment by SagarPC** [comment]
@aharmening  I setup script on the server to update valid/invalid for the EP member. I executed the script manually for now, but onward it will be executed automatically every Saturday at 8:00 PM CST.

1) All active user consider with less than 3-year past Start Date will be considered as valid.
2) All expired user with more than 3-year past or blank Start Date will be considered as invalid.

**Comment by amandagoyette** [comment]
Thanks Sagar.  I’ll test this out and so we can get it wrapped up.

Amanda Harmening
Administrative Assistant/Circulation Specialist
AERA Engine Builders Association
[aera-lr] [EP_2C_186]
