### ISSUE TITLE
Cannot open record

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#57]
When I try to click edit on this record nothing happens.  Please advise:
![image](https://user-images.githubusercontent.com/26386841/75172931-aeec8800-56f3-11ea-9829-0c6d0ec5fbce.png)

**Comment by stellaballa** [comment]
@aharmening  is this the only one account that you can't update? 
@SagarPC  please take a look.

**Comment by amandagoyette** [comment]
@stellaballa  yes it seems to just be that one

**Comment by SagarPC** [comment]
@aharmening  We fixed this issue and now edit it working.

![image](https://user-images.githubusercontent.com/31076567/75235655-97d89380-57e2-11ea-8746-754140a1d492.png)

**Comment by amandagoyette** [comment]
it works thanks!
