### ISSUE TITLE
Renewal form

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#58]
Lately I've had folks emailing that they cannot renew as the form gives them an error when they click the link.  They've all told me that despite entering their phone number correctly with all 10 digits it tells them they need a 10 digit phone number to proceed.  It seems to be an issue specific to the Explorer/Edge browser.  Is this something we can look into?  I don't want to lose renewals because of this.  

Thanks!

**Comment by SagarPC** [comment]
@aharmening  I tried with edge and submit one form and it's working for me.  

Can you please give me more information about one of the EP members who faced this issue and not able to subscribe? It will help me to trobuleshoot this issue.

**Comment by amandagoyette** [comment]
Paul Van Der Linden was one and Ron Sledge was another.  I had no problem with either on Chrome, but they both got the same error.

**Comment by SagarPC** [comment]
@aharmening Thanks for the information. I checked and notice this issue with the IE browser. We fixed and not it's working.

**Comment by amandagoyette** [comment]
@SagarPC Thanks.  I'll close this out.
