### ISSUE TITLE
Update List Drop Down

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#59]
Sagar,

Can you add Retired under the list column for contacts in the EP tab please?

![image](https://user-images.githubusercontent.com/26386841/113753059-48e27a80-96d3-11eb-9941-835df63465bf.png)

**Comment by SagarPC** [comment]
@aharmening We added "Retired" under List Dropdown. Please see the below image for reference.

![image](https://user-images.githubusercontent.com/31076567/114005093-dca37a80-987c-11eb-8f6b-024d449f594f.png)

**Comment by amandagoyette** [comment]
@SagarPC can you move it up above Rock Products so they're still in alphabetical order?  Thanks!

**Comment by SagarPC** [comment]
@aharmening Thanks for the feedback. We updated the order. Please see the below image for reference.

![image (4)](https://user-images.githubusercontent.com/31076567/114144771-4d0cd300-9933-11eb-83f3-5b2e6f6f5c28.png)

**Comment by amandagoyette** [comment]
perfect thanks!
