### ISSUE TITLE
Expiring Contact

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#60]
Sagar,
how hard would it be to change those marked "Expiring" to receive the expired email instead of the 1 issue left email?  As you'll see below these currently default to 1 issue left until their expiration date.  It would be a lot easier for me to get ahead of renewals if I could send a batch of expired emails to them ahead of time.  Thanks! 
![image](https://user-images.githubusercontent.com/26386841/113773261-6c192400-96eb-11eb-862d-1b3d25659e56.png)

**Comment by SagarPC** [comment]
@aharmening  Please see my comment below.

1) As I understand, now onward we want the ability to send an expired email for a list of "Expiring" members, correct?
![image](https://user-images.githubusercontent.com/31076567/113823975-de960c80-979c-11eb-8511-56a3fbf0f789.png)

2) Currently we are sending a 1 Issue Left email for a  list of "Expiring" members. That function we need to remove completely for "Expiring" members OR  we need both "1 Issue Left" and "Expired" email for the "Expiring" members and you will decide which email need to send before click on the final send button.

**Comment by amandagoyette** [comment]
@Sagar ***@***.***> you are correct on which email I want to send.

Yes, remove 1 issue left completely. There is never an instance where I will send it to this group.

Amanda Harmening
Administrative Assistant
AERA Engine Builders Association

________________________________

**Comment by SagarPC** [comment]
@aharmening We made this change and uploaded it on live. Please check and confirm our update. 

![image](https://user-images.githubusercontent.com/31076567/114004975-c3023300-987c-11eb-9d59-99d3ea74affb.png)

![image](https://user-images.githubusercontent.com/31076567/114004997-c72e5080-987c-11eb-964e-825fc55135b9.png)

**Comment by amandagoyette** [comment]
Looks good and works perfect. Thanks!
