### ISSUE TITLE
Update name

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#61]
Hey Sagar.

I got married in June and am working on getting things updated to my new name. Can you change this over to Amanda Goyette instead of Amanda Harmening.  Thanks! 

<img width="341" alt="image" src="https://user-images.githubusercontent.com/26386841/177865355-3690bee9-a87a-4037-83b0-daa0331f25d0.png">

**Comment by SagarPC** [comment]
Hi Amanda,

Congratulation..!

I checked and almost your name is updated on all the places except GitHib. You have to change GitHub name from your end. Please see attached document for the step. It will help you to update name in GitHub.

[update-github-profile.docx](https://github.com/stellaballa/EP/files/9069635/update-github-profile.docx)

Please let me know if any more information required.


Regards,

**Comment by amandagoyette** [comment]
Thank you. I have downloaded the file and will follow it to update accordingly.
