### ISSUE TITLE
Cannot sign up from phone

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#63]
When trying to register this person from my phone I click submit and it just returns to the same screen with all the information filled in. They never appear on my "new" list and I do not get an email. I had Rob try from his phone with his address for a separate test and he had the same results.
![Screenshot_20230112_101648_Samsung Internet](https://user-images.githubusercontent.com/26386841/212195644-9a564daf-8ce1-4b17-84bc-78c697e7ca20.jpg)
Can you look at why this isn't completing the registration.

**Comment by SagarPC** [comment]
@amandagoyette We are looking int to this and will update you asap.

**Comment by SagarPC** [comment]
@amandagoyette  Please check now it should work.

**Comment by amandagoyette** [comment]
Confirmed, it's working. Thanks!
