### ISSUE TITLE
EP Record issue

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#64]
The record attached to the below image isn't working correctly. As you can see behind the pop-up window the state is GA and the country is united states, but when I click edit the popup shows it's missing both state and country and will not let me select the appropriate responses.  Can you fix it?
![image](https://github.com/stellaballa/EP/assets/26386841/6028fedb-3891-42db-bcec-5ee034c432b4)

**Comment by SagarPC** [comment]
@amandagoyette  We are looking into this and get back to you soon.

**Comment by SagarPC** [comment]
@amandagoyette can you please check now? It's showing me GA and USA selected for this record. Please check and let me know if you are facing any other issue with this record.

![image](https://github.com/stellaballa/EP/assets/31076567/9fb645e8-29cc-4886-ae41-e0aec076d1cc)

**Comment by amandagoyette** [comment]
I'm just going into a board meeting I'll check when it's done.

Amanda Goyette
Administrative Assistant
AERA Engine Builders Association
________________________________

**Comment by amandagoyette** [comment]
Good to go. Thank you!
