### ISSUE TITLE
EP Subscription Form

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#65]
Our EP Subscription form found here: https://prosispro.com/EngineProfessional.aspx needs some updating. I believe you need to do this, correct? 
Can we update the form linked at the bottom to the PDF I'm including here? 
[EPSUBSCRIBE.pdf](https://github.com/stellaballa/EP/files/14378086/EPSUBSCRIBE.pdf)

Also, can we change the hyperlink to get there to say fax or email instead of fax or mail?
<img width="542" alt="image" src="https://github.com/stellaballa/EP/assets/26386841/4cb8deb2-e9f0-4d99-9d36-f3581f6d0b68">
Thanks!

**Comment by SagarPC** [comment]
@amandagoyette We are working it and have plan to upload on live by tomorrow.

**Comment by SagarPC** [comment]
@amandagoyette We updated as you requested.

Regards,

**Comment by amandagoyette** [comment]
Checked it out and it all looks good. Thank you!
