### ISSUE TITLE
Engine Professional - Spammed

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#66]
Hi Sagar,

Starting around 1:00pm my time yesterday it seems our Engine Professional request form was spammed. As you'll see in the image below I have over 200 requests that are nothing but email addresses in every field and are tied to the Czech Republic with a state of YK. 
![EP Request form](https://github.com/stellaballa/EP/assets/26386841/e8ca22c2-5a91-413a-bd8b-33c0f8fb6e5d)

I have 2 questions for you:
1. Is there a way you can quickly delete all these so I don't have to go into the system and delete them individually?
2. Is there something we can put into place to help prevent this in the future? I can ask VCS for advice too, but wanted to get your thoughts from a programming standpoint first.

Thanks.

**Comment by SagarPC** [comment]
@amandagoyette We are adding security on that page and will remove all those detail from the database from our end.

I will inform you as soon as possible.

**Comment by amandagoyette** [comment]
Thank you!

**Comment by SagarPC** [comment]
@amandagoyette   We added security on the engine professional page now this thing will not happen again. We also removed all spam data from the EP tab. 

Please check and let us know if any questions.

**Comment by amandagoyette** [comment]
@SagarPC I have checked everything over and it appears to be working and all spam records have been removed. thank you!
