### ISSUE TITLE
Issue with verification portion of EP Sign up

### ISSUE THREAD

**Issue by amandagoyette** [stellaballa/EP#68]
Hi Sagar,
I was trying to help get a subscriber back in the system, and there seems to be an issue with the verification at the bottom. As you can see below I typed in cs4z3b which is what it shows:
<img width="576" alt="image" src="https://github.com/user-attachments/assets/d26a9448-db71-4a89-a827-bb08c0f5c195" />

However, when I hit submit it just updated the characters as though I typed them wrong, and leaves my previous ones in the box:
<img width="574" alt="image" src="https://github.com/user-attachments/assets/e30724f7-2ec7-4945-b681-f633f8f880c7" />

Can you look into this? 

Thanks, Amanda

**Comment by SagarPC** [comment]
@amandagoyette 
Which browser you are using and what is the OS. It will help us to look into it. We checked with Google Chrome and it’s working for us.

**Comment by amandagoyette** [comment]
@SagarPC Sorry about that. I use Chrome exclusively if I can help it!

**Comment by amandagoyette** [comment]
I will try and reboot and see if that fixes it. If not I'll try clearing my Cache, etc. I'll report back.

**Comment by amandagoyette** [comment]
Something must have been hung up on my end a hard shutdown did the trick. Thanks for checking!
