### ISSUE TITLE
Expired - Why all have 1 issue left?

### ISSUE THREAD

**Issue by stellaballa** [stellaballa/EP#7]
Why all expired have 1 issue left? If the account have expired last year, there shouldn't have any issue left. But all account expired in Dec. so It's either a data thing, or something is not right with expried account filter. 

![screen shot 2018-11-05 at 2 09 54 pm](https://user-images.githubusercontent.com/30122790/48030043-bb1a9380-e104-11e8-84f8-107fd09d45bf.png)

**Comment by SagarPC** [comment]
@stellaballa : As we discussed and as per your given comment in the meeting, we consider user as expired only once the quarter is completed. All those user dates are expired but the quarter is working. 

Please let us know if there is any change in this logic. I think the client also want the same logic.

**Comment by stellaballa** [comment]
@SagarPC ok there's miss communication on this. There should be 3 catagories
1) 1 Issue Left (Next Qt) - Which means this user has 2 issue left. 
2) Expiring (1 issue left this Qt)
3) Expired (No issue left) but we need to keep their original expiration date.

**Comment by SagarPC** [comment]
@stellaballa :

I know about this 3 things but here an issue with which user we need to consider under which case. 

Please give us the answer (where I added ?? mark) on below cases to be more clear.

Consider  **Current Working Quarter:**  1st SEP 2018 to 31 DEC 2018 & **Today's Date is** 11th NOV 2018.

**If User A Exp. Date: 4th SEP 2018 then** 
    1. Issue Left (Next Qt) - Which means this user has 2 issue left. >> False
    2. Expiring (1 issue left this Qt) >> ??
    3. Expired (No issue left) but we need to keep their original expiration date. >> ??

**If User B Exp. Date: 11th OCT 2018 then** 
    1. Issue Left (Next Qt) - Which means this user has 2 issue left. >> False
    2. Expiring (1 issue left this Qt) >> ??
    3. Expired (No issue left) but we need to keep their original expiration date. >> ??


**If User C Exp. Date: 02nd JAN 2019 then** 
    1. Issue Left (Next Qt) - Which means this user has 2 issue left. >> True
    2. Expiring (1 issue left this Qt) >> False
    3. Expired (No issue left) but we need to keep their original expiration date. >> 02nd JAN 2019

**Comment by stellaballa** [comment]
@SagarPC just discussed this with the client. And this is what we will do:

1) Expired
No Issue left with an expiration date. For example, if today's date is 11th Nov 2018 and this person's account expired 11th Nov 2017 with no issue left. 

2) Subscription Expiring
Anyone who has 1 issue left this quarter. 

3) 1 Issue Left
Anyone who has 1 issue left next quarter.

**Comment by anthonypartsconnect** [comment]
@SagarPC 
Please let us know if anything else is needed on your end. 

Thanks. 

Anthony

**Comment by SagarPC** [comment]
@anthonypartsconnect : We uploaded logic as requested and uploaded on stage. Please check and confirm our update.

Expired
![image](https://user-images.githubusercontent.com/31076567/48484998-ad1fed80-e83d-11e8-96d4-fc698b86c0cd.png)

Subscription Expiring
![image](https://user-images.githubusercontent.com/31076567/48485063-dccef580-e83d-11e8-8b53-e60cd86f35a7.png)

1 Issue Left
![image](https://user-images.githubusercontent.com/31076567/48485123-0425c280-e83e-11e8-9f7f-24da5670bf67.png)

**Comment by stellaballa** [comment]
@aharmening can you please check and see if this logic is working correctly?

**Comment by amandagoyette** [comment]
@stellaballa Yes, the right dates are under 1 issue left, expiring, and lapsed.  

Is there a reason the dates all default to the end of the month for the expiration? Would it be easy to keep it at the 3 years from the date of subscription? For example, if someone subscribed on 11/2/15 they should have expired on 11/2/18.

**Comment by stellaballa** [comment]
@SagarPC please make sure the expiration dates are 3 years from the subscription date.

**Comment by SagarPC** [comment]
@stellaballa  @aharmening  

At the time of new user subscription or edit start date we are doing same as you suggested but when AERA MMS user taking action to set "1 issue left" forcefully at that time we don't have any specific date to set and because of that, we are considering the last date of next quarter. Please suggest if any change in this process.

![image](https://user-images.githubusercontent.com/31076567/48544191-190b6000-e8e9-11e8-858d-648c538292e3.png)

**Comment by amandagoyette** [comment]
@SagarPC When it is forced the last date of the next quarter is perfect.

**Comment by SagarPC** [comment]
@aharmening It's working on stage as you suggested. Please confirm our update.

**Comment by amandagoyette** [comment]
Looks good!
