### ISSUE TITLE
Change 1 issue left - Shouldn't sent out Thank you email

### ISSUE THREAD

**Issue by stellaballa** [stellaballa/EP#8]
After I changed my account to 1 issue left, this pop up said, Are you sure you want to send thank you email? 
Why are we sending thank you email? Please remove. But we should have an option for "Would you like to send this user a subscription request?" Yes or No. 

![screen shot 2018-11-05 at 2 14 41 pm](https://user-images.githubusercontent.com/30122790/48030204-30866400-e105-11e8-94f9-b006b1b15466.png)

**Comment by SagarPC** [comment]
@stellaballa: removed e-thank you confirmation and showing "subscription request" on the selection of 1 issue left. 

Please consider "subscription request" prompt showing only once the user selects this checkbox manually.
