### ISSUE TITLE
Update Info, after save, the message for send thank you email show up

### ISSUE THREAD

**Issue by stellaballa** [stellaballa/EP#9]
Please don't send Thank you email to the user every time if AERA update the changes. 
An email should be sent automatically once the user has been subscribe. Which is working right now. 

![screen shot 2018-11-05 at 2 21 09 pm](https://user-images.githubusercontent.com/30122790/48030584-624bfa80-e106-11e8-91e8-daf13e1cc55c.png)

**Comment by SagarPC** [comment]
removed confirmation box from the AERAMMS as sending subscription email at the time of registration.

**Comment by anthonypartsconnect** [comment]
@SagarPC, were you able to disable communication to the user for every change?   

We only want the emails going to users when they subscribe.

**Comment by SagarPC** [comment]
@anthonypartsconnect : We already have taken action on this and it's uploaded on stage. Please check and confirm our update.

**Comment by stellaballa** [comment]
@anthonypartsconnect please check
